<a href="https://colab.research.google.com/github/manmeet3591/python_class/blob/master/xarray_tutorial/cape_cin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#!pip install siphon
from datetime import datetime
from siphon.simplewebservice.wyoming import WyomingUpperAir

In [4]:
df = WyomingUpperAir.request_data(datetime(2012,4,14,12), 'OUN')

In [5]:
df

     pressure  height  temperature  ...  longitude  elevation     pw
0       969.0     345         21.0  ...     -97.44      345.0  29.21
1       964.0     390         20.8  ...     -97.44      345.0  29.21
2       939.6     610         19.1  ...     -97.44      345.0  29.21
3       925.0     744         18.0  ...     -97.44      345.0  29.21
4       906.8     914         16.6  ...     -97.44      345.0  29.21
..        ...     ...          ...  ...        ...        ...    ...
117      10.8   30480        -43.1  ...     -97.44      345.0  29.21
118      10.5   30681        -42.5  ...     -97.44      345.0  29.21
119      10.0   31010        -42.9  ...     -97.44      345.0  29.21
120       9.0   31699        -44.4  ...     -97.44      345.0  29.21
121       8.8   31868        -44.7  ...     -97.44      345.0  29.21

[122 rows x 15 columns]

In [7]:
#!pip install metpy

In [8]:
from metpy.units import units

In [10]:
p = df['pressure'].values * units(df.units['pressure'])
T = df['temperature'].values * units(df.units['temperature'])
Td = df['dewpoint'].values * units(df.units['dewpoint'])
heights = df['height'].values * units(df.units['height'])

In [11]:
import metpy.calc as mpcalc

In [12]:
mpcalc.surface_based_cape_cin(p, T, Td)

(1153.8204819179555 joule/kilogram, -8.634797296894165 joule/kilogram)

In [13]:
p

array([969. , 964. , 939.6, 925. , 906.8, 904. , 874.9, 850. , 844. ,
       819. , 814. , 784.8, 757. , 756.8, 729.1, 722. , 700. , 690. ,
       661. , 652. , 651.5, 638. , 603.6, 558.9, 550. , 514. , 500. ,
       496.6, 476.8, 410. , 405.2, 400. , 394. , 388.6, 386. , 373. ,
       326. , 313.2, 300. , 299.6, 261.4, 250. , 200. , 196.4, 196. ,
       189. , 188. , 182. , 169.2, 166. , 150. , 145.3, 142. , 137. ,
       131.3, 131. , 130. , 126. , 122. , 119. , 114. , 113.3, 108. ,
       106. , 104. , 102. , 100. ,  80.7,  76.1,  74.2,  72.4,  70. ,
        68.8,  67.6,  65.5,  63.7,  62.3,  59.2,  58.5,  56.3,  50. ,
        49.3,  48.5,  43.9,  43.2,  39.8,  37.9,  37.4,  36.1,  34.4,
        33.5,  32.8,  31.2,  30.7,  30. ,  29.1,  28.4,  27.1,  27.1,
        25.8,  25.5,  23.6,  23.1,  21.5,  20.3,  20. ,  19.6,  18.7,
        18.3,  17.1,  17.1,  15.7,  14.9,  14.4,  14. ,  12.1,  11.4,
        10.8,  10.5,  10. ,   9. ,   8.8]) hectopascal

In [14]:
T

array([ 21. ,  20.8,  19.1,  18. ,  16.6,  16.4,  15. ,  13.8,  13.6,
        12.6,  12.3,  10.2,   8.2,   8.2,   4.6,   3.6,   4.8,   5.2,
         3.4,   3. ,   3. ,   2.2,  -1.1,  -5.6,  -6.5, -11.1, -12.3,
       -12.7, -14.7, -22.5, -23.2, -23.9, -24.7, -25.1, -25.3, -27.3,
       -35.3, -37.5, -39.9, -40. , -47.3, -49.7, -61.5, -62.4, -62.5,
       -63.5, -62.5, -63.1, -66.9, -67.9, -68.5, -68.6, -68.7, -67.9,
       -63.6, -63.3, -63.2, -62.7, -60.9, -61.1, -61.5, -61.5, -61.3,
       -60.3, -61.1, -59.9, -60.5, -68.3, -65.9, -64.9, -65.5, -66.3,
       -66.7, -67.1, -65.7, -64.5, -65.3, -67.1, -67.5, -66.7, -64.3,
       -63.7, -63.7, -63.5, -63.5, -60.3, -58.4, -57.9, -58.2, -58.5,
       -58.7, -58.3, -57.4, -57.1, -55.5, -53.1, -52. , -50.1, -50.1,
       -50.6, -50.7, -47.3, -46.5, -46.8, -47.1, -46.3, -45.7, -46.9,
       -47.5, -45.8, -45.7, -48.1, -47.1, -46.5, -44.1, -42.9, -44.1,
       -43.1, -42.5, -42.9, -44.4, -44.7]) degree_Celsius

In [15]:
Td

array([ 18.2,  18.3,  17.8,  17.5,  16.6,  16.4,  15. ,  13.8,  13.6,
        12.6,  12.3,  10.2,   8.2,   7.9, -24. , -32.4, -29.2, -21.8,
       -23.6, -46. , -46. , -46.8, -43.7, -39.4, -38.5, -23.1, -25.3,
       -25.9, -29.2, -41.5, -40.3, -38.9, -39.7, -44.8, -47.3, -62.3,
       -62.3, -62.6, -62.9, -62.9, -65.8, -66.7, -74.5, -75.4, -75.5,
       -76.5, -75.5, -76.1, -79.1, -79.9, -80.5, -80.6, -80.7, -79.9,
       -76.5, -76.3, -76.2, -75.7, -74.9, -75.5, -76.5, -76.6, -77.3,
       -76.3, -77.1, -76.9, -77.5, -83.3, -82.3, -81.9, -82.5, -83.3,
       -83.7, -84.1, -83.2, -82.5, -83. , -84.2, -84.5, -84.7, -85.3,
       -85.7, -86.2, -89. , -89.5, -89.7, -89.9, -89.9, -89.8, -89.8,
       -89.7, -89.5, -89.2, -89.1, -87.5, -86.1, -85.4, -84.1, -84.1,
       -84.6, -84.7, -82.1, -81.5, -81.8, -82.1, -81.3, -80.7, -81.9,
       -82.5, -80.7, -80.7, -82.1, -81.7, -81.5, -80.1, -78.9, -80.1,
       -79.1, -78.5, -78.9, -79.5, -79.7]) degree_Celsius

In [16]:
mpcalc.most_unstable_cape_cin(p, T, Td)

(1400.0053934540974 joule/kilogram, -0.1321154666668731 joule/kilogram)